  version: 0.2

  phases:
    pre_build:
      commands:
        aws s3 rm  --recursive s3://azma.io --exclude "azma/afterAUTH.html"
    build:
      commands:


  artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist
