  version: 0.2

  phases:
    pre_build:
      commands:
    build:
      commands:
        - echo `$BUILD_COMMAND`


  artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist
